### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by dcfyg** [avafinger/OV5640_camera#1]
Hi Avafinger, 

I am interested in your work with the OV5640. I was looking for an email address but I couldn't find any. This is why I am trying to contact you this way. Could you please provide me with an email address where I can send you a message? 

Thanks in advance. 

Best regards, 
Daniel

**Comment by dcfyg** [comment]
@avafinger

**Comment by avafinger** [comment]
a l e x (dot) m o b i g o at g m a i l (dot) c o m
BTW, you can find the sources at https://github.com/avafinger/ov5640  just choose the correct branch.
